name: Frontend Continuous Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGION: ${{ secrets.AWS_REGION }}
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: ${{ secrets.ECR_REPO_FRONTEND }}
  CLUSTER: ${{ secrets.EKS_CLUSTER_NAME }}
  NAMESPACE: ${{ secrets.K8S_NAMESPACE }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm install
      - run: npm run lint
      - run: npm test -- --ci --watchAll=false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build image (with API URL)
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="${{ secrets.REACT_APP_MOVIE_API_URL }}" \
            -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:${{ github.sha }} \
            .

      - name: Push image
        run: docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER }} --region ${{ env.REGION }}

      - name: Set image & rollout
        run: |
          kubectl set image deployment/frontend-deployment frontend=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:${{ github.sha }} -n $NAMESPACE
          kubectl rollout status deployment/frontend-deployment -n $NAMESPACE
